### ISSUE TITLE
Error while testing the edited template

### ISSUE THREAD

**Issue by nikopartanen** [pyannote/pyannote-db-template#1]
I noticed that Tensorflow installation is not mentioned in [this tutorial](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/speech-activity-detection). Following the instructions I get an error:

    ImportError: No module named 'tensorflow'

I installed it now with  `pip install tensorflow`.

I have modified the template [like this](https://github.com/langdoc/pyannote-db-ikdp), and I try to do the training with:

    export EXPERIMENT_DIR=experiment
    pyannote-speech-detection train ${EXPERIMENT_DIR} ikdp.SpeakerDiarization.MyFirstProtocol

The error I'm getting is right in the beginning of the first epoch, here is the complete output:

    Using TensorFlow backend.
    /Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/database/util.py:193: UserWarning: "annotated" was approximated by "wav" duration.
      warnings.warn('"annotated" was approximated by "wav" duration.')
    2017-07-13 16:43:05.736378: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-13 16:43:05.736413: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-13 16:43:05.736420: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-13 16:43:05.736427: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/keras/engine/training.py", line 429, in data_generator_task
        generator_output = next(self._generator)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/generators/batch.py", line 416, in __call__
        raise e
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/generators/batch.py", line 409, in __call__
        current_file, identifier=uri)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/generators/speech.py", line 86, in preprocess
        coverage = annotation.get_timeline().coverage()
    AttributeError: 'Timeline' object has no attribute 'coverage'
    
    Epoch 1/1000
    Traceback (most recent call last):
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/bin/pyannote-speech-detection", line 11, in <module>
        sys.exit(main())
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/speech_detection.py", line 522, in main
        application.train(protocol_name, subset=subset)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/speech_detection.py", line 297, in train
        optimizer=SSMORMS3(), log_dir=train_dir)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/labeling/base.py", line 153, in fit
        verbose=1, callbacks=callbacks)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/keras/engine/training.py", line 1532, in fit_generator
        str(generator_output))
    ValueError: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None

There are some variations of the error message depending on what I try, but invariably present error message is always that on the last line.

I didn't put my mdtm file yet to GitHub as I may want to anonymize the identifiable info that is in the speaker id's first, but it looks basically like example below, I was also thinking the problem could be related to it somehow. For now I selected recordings which are completely annotated:

    file20090222 1 0.0 1.663 speaker NA unknown aaa
    file20090222 1 1.663 2.289 speaker NA unknown aaa
    file20090222 1 3.952 1.256 speaker NA unknown aaa
    file20150402-7-b 1 2005.1 4.206 speaker NA unknown bbb
    file20150402-7-b 1 2009.261 2.112 speaker NA unknown ccc
    file20150402-7-b 1 2011.32 0.52 speaker NA unknown bbb

It is entirely possible that I have just missed some clear instruction somewhere, I appreciate if pointed to the right direction if that's the case. Thank you! Merci!

**Comment by hbredin** [comment]
Thanks for reporting this. I need to update this tutorial. Will do...
I think updating `pyannote.audio` to 0.3.1 (latest version) will solve your problem.
Let me know and I will update the tutorial accordingly.

**Comment by nikopartanen** [comment]
Thank you a lot, this works perfectly! I'm now testing the training.

I noticed there is a typo on line 33 in file [pyannote/audio/generators/speech.py](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/generators/speech.py): from pyannote.data**bse**.util import get_annotated. After changing this everything worked as expected.

**Comment by hbredin** [comment]
Thanks for reporting the typo. Will fix it next release.

**Comment by nikopartanen** [comment]
Thank you! I tested the later parts of the tutorial over the weekend, and these are the messages I currently get. I'm getting with the tuning part messages:

    Iteration No: 1 ended. Evaluation done at provided point.
    Time taken: 3.3038
    Function value obtained: 0.0000
    Current minimum: 0.0000
    Iteration No: 2 started. Evaluating function at random point.
    /Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/keras/models.py:245: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
      warnings.warn('No training configuration found in save file: '
    /Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/skopt/optimizer/optimizer.py:195: UserWarning: The objective has been evaluated at this point before.
      warnings.warn("The objective has been evaluated "
      ... (the same message repeated)
      Iteration No: 20 ended. Search finished for the next optimal point.
    Time taken: 8.3426
    Function value obtained: 0.0000
    Current minimum: 0.0000
    Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x12d522a58>>
    Traceback (most recent call last):
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 582, in __del__
    AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'

There were many more epochs, so I don't know why it goes through only 20, but it still succesfully creates the tune.yml file. I don't know if this is related to later error I get with apply-phase:

    /Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/keras/models.py:245: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
      warnings.warn('No training configuration found in save file: '
    Test set: 0it [00:00, ?it/s]
    Traceback (most recent call last):
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/bin/pyannote-speech-detection", line 11, in <module>
        sys.exit(main())
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/speech_detection.py", line 615, in main
        application.apply(protocol_name, subset=subset)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/speech_detection.py", line 565, in apply
    precomputed = Precomputed(root_dir=apply_dir)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/features/utils.py", line 110, in __init__
        start = f.attrs['start']
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2846)
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2804)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
        attr = h5a.open(self._id, self._e(name))
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2846)
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2804)
      File "h5py/h5a.pyx", line 77, in h5py.h5a.open (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/h5a.c:2343)
    KeyError: "Can't open attribute (Can't locate attribute: 'start')"

I also wonder what is the desired folder structure, since now it seems to be deeply nested, but I'm not sure if this is intended or am I setting the paths somehow wrong. I'll try it soon again with very small amount of data in a new clean environment, so I'll update this if something changes.

**Comment by hbredin** [comment]
I guess these are two different issues for `pyannote.audio` rather than `pyannote.db.template`.
Can you please open two new issues in `pyannote.audio` (one for tune mode, one for apply mode)? 

The deeply nested folder structure is expected (it allows to get a clear idea of what database/protocol were used for each train/tune/apply mode).

**Comment by nikopartanen** [comment]
Just opened those, [here](https://github.com/pyannote/pyannote-audio/issues/39) and [here](https://github.com/pyannote/pyannote-audio/issues/40). Thanks for the instructions! This issue can probably be closed then.
